apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: ungacr.azurecr.io/product:latest
          ports:
            - containerPort: 8080
